<a href="https://www.kaggle.com/code/riteshkumarweb/bagging-classifier-ensemble-learning?scriptVersionId=319285708" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/shravan3273/breast-cancer-classifiction/breastcancer.csv


In [24]:
# 📊 Bagging (Bootstrap Aggregating)

# Bagging is an Ensemble Learning technique

# 🎯 Goal:
# Improve accuracy and reduce overfitting

# 🧠 Idea:
# Train multiple models on different random subsets
# of the dataset and combine their predictions

# 📦 Bootstrap:
# Random sampling WITH replacement

# Means:
# Same data point can appear multiple times
# in one sampled dataset

# 📊 Aggregating:
# Combine predictions from all models

# For Classification:
# → Majority Voting 🗳️

# For Regression:
# → Average Prediction 📈


# 🔁 Working of Bagging:

# Step 1️⃣
# Create multiple random datasets from original data

# Step 2️⃣
# Train separate models on each dataset

# Step 3️⃣
# Collect predictions from all models

# Step 4️⃣
# Combine predictions for final output


# 📦 Commonly used with:
# 🌳 Decision Trees

# Example:
# Random Forest = Bagging + Decision Trees


# 🎯 Advantages:
# ✅ Reduces overfitting
# ✅ Improves stability
# ✅ Better accuracy
# ✅ Works well on high variance models

# ❌ Disadvantages:
# ❌ Slower
# ❌ More memory usage
# ❌ Less interpretable


# 📊 Simple Diagram:

#                📥 Original Dataset
#                         │
#       ┌─────────────────┼─────────────────┐
#       │                 │                 │
#   📦 Sample1        📦 Sample2        📦 Sample3
#       │                 │                 │
#    🌳 Tree1          🌳 Tree2          🌳 Tree3
#       │                 │                 │
#       └─────────────────┼─────────────────┘
#                         │
#               🗳️ Voting / Averaging
#                         │
#                  ✅ Final Prediction

In [2]:
df = pd.read_csv('/kaggle/input/datasets/shravan3273/breast-cancer-classifiction/breastcancer.csv')

In [3]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [4]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [5]:
df.drop(columns=['id'],inplace=True)

In [6]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [7]:
X = df.iloc[:,1:]
X 

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400


In [8]:
y = df.iloc[:,0]
y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [9]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['diagnosis'] = encoder.fit_transform(y)

In [10]:
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train,y_train)
y_pred = dt.predict(X_test)

print("Decision Tree accuracy", accuracy_score(y_test,y_pred))

Decision Tree accuracy 0.9473684210526315


In [11]:
X_train.shape

(455, 30)

In [12]:
y_train.shape

(455,)

# **Type of Bagging**

In [13]:
# =========================================================
#              TYPES OF ENSEMBLE LEARNING
# =========================================================


# 1️⃣ BAGGING
# ---------------------------------------------------------
#
#          Random Samples from Dataset
#
#        ┌────────┬────────┬────────┐
#        ▼        ▼        ▼
#      Tree1    Tree2    Tree3
#
#        └────────┼────────┘
#                 ▼
#          Voting / Average
#                 ▼
#          Final Prediction
#
# Goal:
# - Reduce Variance
# - Reduce Overfitting
#
# Example:
# - Random Forest
#
# =========================================================


# 2️⃣ BOOSTING
# ---------------------------------------------------------
#
#          Model 1
#             ▼
#      Correct Mistakes
#             ▼
#          Model 2
#             ▼
#      Correct Mistakes
#             ▼
#          Model 3
#             ▼
#      Final Prediction
#
# Goal:
# - Reduce Bias
#
# Examples:
# - AdaBoost
# - XGBoost
#
# =========================================================


# 3️⃣ VOTING
# ---------------------------------------------------------
#
#        KNN  ────┐
#        Tree ────┼──► Voting ─► Final Prediction
#        SVM  ────┘
#
# Goal:
# - Combine Different Algorithms
#
# =========================================================


# 4️⃣ STACKING
# ---------------------------------------------------------
#
#        KNN  ────┐
#        Tree ────┼──► Meta Model ─► Final Prediction
#        SVM  ────┘
#
# Goal:
# - Learn Best Combination of Models
#
# =========================================================

# Simple Bagging with DicisionTree

In [14]:
bag_a = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=0.25, #Taking 25% random samples for each model
bootstrap=True, #Enabling sampling with replacement
random_state=42 #Fixing random behavior for same results
)
bag_a.fit(X_train ,y_train)
y_pred = bag_a.predict(X_test)
accuracy_score(y_test,y_pred)

0.956140350877193

⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

In [15]:
#                  BAGGING WORKFLOW
#
#               Original Dataset
#             X_train = 455 Rows
#
#          ┌──────────────────────┐
#          │      455 Rows        │
#          └──────────────────────┘
#                     │
#     ┌───────────────┼───────────────┐
#     │               │               │
#     ▼               ▼               ▼
#
# Random Sample   Random Sample   Random Sample
#   (~114 rows)     (~114 rows)     (~114 rows)
#
#     │               │               │
#     ▼               ▼               ▼
#
#   Tree 1          Tree 2          Tree 3
#
#     │               │               │
#     └───────────────┼───────────────┘
#                     ▼
#
#              Majority Voting
#                     ▼
#
#              Final Prediction
#
#
# IMPORTANT:
# - Dataset is NOT divided equally ❌
# - Each tree randomly samples data ✅
# - Same row can appear many times ✅
# - bootstrap=True → repetition allowed

# Bagging using SVM

In [16]:
from sklearn.svm import SVC

bag_b = BaggingClassifier(
estimator=SVC(),
n_estimators=500,
max_samples=0.25,
bootstrap=True,
random_state=42)

bag_b.fit(X_train,y_train)
y_pred = bag_b.predict(X_test)
print("Bagging using SVM", accuracy_score(y_test,y_pred))

Bagging using SVM 0.9385964912280702


⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

# Pasting 
Same as simple bagging or bagging but no reapeated sample so 
bootstrap = False , sample means random data from the point not sequence
wise,like we do  **df.sample(10)** like this 

In [17]:
bag_c = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=0.25, #Taking 25% random samples for each model
bootstrap=False, #Disabling sampling with replacement
random_state=42, #Fixing random behavior for same results
#verbose=1, #Showing training progress information
n_jobs=1 #Using all CPU cores for faster processing
)
,
bag_c.fit(X_train,y_train)
y_pred = bag_c.predict(X_test)
print("Pasting classifier", accuracy_score(y_test,y_pred))

Pasting classifier 0.956140350877193


⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

# Random Subspaces
Instead of Row Sampling rows , we do feature/columns sampling(shuffle) . if data has Age salary, Height ,Wight, then , one model may train on Age+ Height and another on salary+ Weight. 

In [18]:
bag_d = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=1.0, #Using 100% rows from training data for each model
bootstrap=False, #Disabling sampling with replacement for rows
max_features=0.5, #Taking 50% random features/columns for each model
    #if the datset has 30 features or column then it randomdly select
    #15 column is it set to 0.5 
bootstrap_features=True, #Enabling sampling with replacement for features
random_state=42 #Fixing random behavior for same results
)

bag_d.fit(X_train,y_train)
y_pred = bag_d.predict(X_test)
print("Random Subspaces classifier", accuracy_score(y_test,y_pred))

Random Subspaces classifier 0.9649122807017544


⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

In [19]:
bag_d.estimators_features_ # index number of columns who is randomdly selected

[array([27,  9, 26, 10, 12,  2,  9,  7, 28,  7, 24, 19, 18, 24, 29]),
 array([14, 23, 19, 23, 19, 25,  5, 10,  3,  9, 15, 10, 16, 19,  8]),
 array([22, 14,  0,  7,  7, 25, 26,  8, 28, 21, 24, 18, 21, 14, 20]),
 array([ 0,  5, 23, 10, 12,  4, 17, 19, 22, 18, 21, 11,  3, 17,  2]),
 array([13,  6, 25,  6, 11,  3, 15,  3,  8,  3, 23,  8, 22, 26, 16]),
 array([21, 18,  1, 18,  7, 25, 19, 13, 13, 17, 13,  3, 15,  6, 17]),
 array([12, 12, 19, 29,  2, 10, 17, 21,  2,  3, 17,  5,  5, 26, 15]),
 array([14, 11,  6, 18, 24, 14,  2,  5, 25, 16, 20, 15, 26, 15,  3]),
 array([ 8, 28, 12, 10, 29,  4, 13, 20,  3, 13, 18, 12, 19, 22, 12]),
 array([ 8, 13, 17, 24, 14,  9, 28, 16,  7, 22, 26, 14, 26, 12,  8]),
 array([19, 18,  9, 24,  4, 11,  6, 22, 28, 28, 19, 28,  4,  2, 23]),
 array([ 4, 23, 24, 22, 10, 23, 14, 17, 12,  9, 23,  2,  8, 21, 28]),
 array([19,  9, 26, 10, 29,  4,  8, 13, 10, 27,  6,  1,  5, 13, 15]),
 array([ 0, 25, 29, 22,  7, 14,  4,  0,  5,  9, 28, 13, 29, 25,  5]),
 array([16, 13,  8, 

# Random Patches
Combination of row sampling and column/features sampling 

In [20]:
bag_e = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=0.25, #Taking 25% random rows for each model
bootstrap=True, #Enabling sampling with replacement for rows
max_features=0.5, #Taking 50% random features for each model
bootstrap_features=True, #Enabling sampling with replacement for features
random_state=42 #Fixing random behavior for same results
)
bag_e.fit(X_train,y_train) 
y_pred = bag_e.predict(X_test) 
print("Random Patches classifier", accuracy_score(y_test,y_pred))

Random Patches classifier 0.9649122807017544


⚠️ IMPORTANT:
 - Dataset is NOT divided equally ❌
 - Each tree randomly samples data ✅ or select data from the dataset 
 - Same row can appear many times ✅ if bootsrap is true 
 - bootstrap=True → repetition allowed

# OBB score
OOB Score (Out-Of-Bag Score) is the accuracy or performance of a bagging model measured using the rows/samples that were not selected during bootstrap training of a particular tree or estimator. you can say that like the X_test

⚠️ OOB works with:
✅ rows/samples
❌ not columns/features

🔥 Used mainly in:
Bagging
Random Forest

In [21]:
bag_e = BaggingClassifier(
estimator=DecisionTreeClassifier(), #Creating Decision Tree as base estimator
n_estimators=500, #Creating 500 Decision Tree models
max_samples=0.25, #Taking 25% random rows for each model
bootstrap=True, #Enabling sampling with replacement
oob_score=True, #Enabling Out Of Bag score calculation
max_features=0.5,   
random_state=42 #Fixing random behavior for same results
)
bag_e.fit(X_train,y_train)
y_pred_e = bag_e.predict(X_test)

In [22]:
print("Random Patches classifier", accuracy_score(y_test,y_pred_e))
print(('OBB score is ',bag_e.oob_score_))

Random Patches classifier 0.9649122807017544
('OBB score is ', 0.9560439560439561)


Bagging Tips

- Bagging generally gives better results than Pasting
- Good results come around the 25% to 50% row sampling mark
- Random patches and subspaces should be used while dealing with high dimensional data
- To find the correct hyperparameter values we can do GridSearchCV/RandomSearchCV

# Apply GridSearch To Find best hyperparamer and best results

In [23]:
from sklearn.model_selection import GridSearchCV

parameters = {
'n_estimators': [50,100,500],
'max_samples': [0.1,0.4,0.7,1.0],
'bootstrap' : [True, False],
'max_features' : [0.1,0.4,0.7,1.0] }

search = GridSearchCV(BaggingClassifier(), parameters, cv=5)

search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=BaggingClassifier(),
             param_grid={'bootstrap': [True, False],
                         'max_features': [0.1, 0.4, 0.7, 1.0],
                         'max_samples': [0.1, 0.4, 0.7, 1.0],
                         'n_estimators': [50, 100, 500]})

In [25]:
search.best_params_

{'bootstrap': True,
 'max_features': 0.7,
 'max_samples': 0.7,
 'n_estimators': 50}

In [26]:
search.best_score_

np.float64(0.9626373626373625)