<a href="https://www.kaggle.com/code/riteshkumarweb/xgboost-classification-regression?scriptVersionId=322319221" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [40]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sreekargv/bike-rentals/Yulu.csv
/kaggle/input/datasets/riteshkumarweb/accident-dataset/Cas.csv


In [ ]:
# ⚡ XGBoost (Extreme Gradient Boosting)

# XGBoost is an advanced and optimized version
# of Gradient Boosting

# 🎯 Goal:
# High accuracy
# Fast training
# Better performance

# 🧠 Idea:
# Train trees sequentially
# where each new tree fixes
# errors made by previous trees

# XGBoost improves Gradient Boosting by:
# ✅ Regularization
# ✅ Parallel processing
# ✅ Faster computation
# ✅ Better optimization
# ✅ Handling missing values


# ⚡ XGBoost Classifier

# Used for Classification problems

# Example:
# Spam Detection 📧
# Disease Prediction 🏥
# Fraud Detection 💳

# Final prediction:
# Combined prediction from all trees


# ⚡ XGBoost Regressor

# Used for Regression problems

# Example:
# House Price 🏠
# Salary 💰
# Sales Prediction 📈

# Final prediction:
# Sum of predictions from all trees


# 📦 Important Hyperparameters:

# n_estimators
# → Number of trees

# learning_rate
# → Contribution of each tree

# max_depth
# → Maximum depth of each tree

# subsample
# → Fraction of samples used for each tree

# colsample_bytree
# → Fraction of features used for each tree

# gamma
# → Minimum loss reduction required for split

# reg_alpha
# → L1 Regularization (Lasso)

# reg_lambda
# → L2 Regularization (Ridge)

# random_state
# → Ensures reproducible results


# 📊 XGBoost Classifier Example

from xgboost import XGBClassifier

model = XGBClassifier(

    n_estimators=100,
    # 🌳 Number of trees

    learning_rate=0.1,
    # ⚡ Learning contribution

    max_depth=3,
    # 🌲 Maximum tree depth

    random_state=42
    # 🔁 Reproducible results
)


# 📊 XGBoost Regressor Example

from xgboost import XGBRegressor

model = XGBRegressor(

    n_estimators=100,
    # 🌳 Number of trees

    learning_rate=0.1,
    # ⚡ Learning contribution

    max_depth=3,
    # 🌲 Maximum tree depth

    random_state=42
    # 🔁 Reproducible results
)


# ✅ Advantages:
# Very high accuracy
# Fast and optimized
# Handles missing values
# Reduces overfitting with regularization
# Excellent for tabular data

# ❌ Disadvantages:
# Hyperparameter tuning is complex
# Training can be slower on huge datasets
# Harder to interpret


# 📊 Simple Diagram:

#          📥 Original Dataset
#                   │
#              🌳 Tree1
#                   │
#            ❌ Residuals
#                   │
#              🌳 Tree2
#                   │
#            ❌ Residuals
#                   │
#              🌳 Tree3
#                   │
#         ➕ Add Predictions
#                   │
#            ✅ Final Prediction

In [41]:
from sklearn.datasets import make_s_curve
X,y = make_s_curve(n_samples=10000 , noise=0.05, random_state=42)
X

array([[-0.96571966,  0.70343478,  0.6498135 ],
       [-0.86474307,  0.64379835, -1.4402766 ],
       [ 0.88168625,  0.29291892, -1.55011731],
       ...,
       [-0.82208863,  0.50871989, -1.46659781],
       [-0.72510553,  0.87853085,  0.38251414],
       [-0.44688208,  0.35205608,  1.90468338]])

In [42]:
X.shape

(10000, 3)

In [43]:
y.shape

(10000,)

In [44]:
from sklearn.model_selection import train_test_split

# X = features, y = target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Applying LinarRegression to the dataset 

In [45]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score 
from sklearn.model_selection import cross_val_score 
reg = LinearRegression()
reg.fit(X_train,y_train)
y_reg_predict = reg.predict(X_test)
score = r2_score(y_test,y_reg_predict)
print('The r2_score for this dataset with XGboost',score)
cv_result = cross_val_score(reg,X,y,scoring='r2',cv=10,n_jobs=-1 )
print('The mean of cross val score with r2_score with XGBoost',np.mean(cv_result))


The r2_score for this dataset with XGboost 0.938681425788173
The mean of cross val score with r2_score with XGBoost 0.9385578390220888


# Applying XGBoost Regressor to the dataset 

In [46]:
from xgboost import XGBRegressor 
model = XGBRegressor( n_estimators=300,learning_rate=0.05,max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    device='cpu',
    random_state=42)
model.fit(X_train, y_train)
# 4. Make predictions
predictions = model.predict(X_test)
score = r2_score(y_test,predictions)
print('The r2_score for this dataset with XGboost',score)
cv_result_x = cross_val_score(model,X,y,scoring='r2',cv=10,n_jobs=-1 )
print('The mean of cross val score with r2_score with XGBoost',np.mean(cv_result_x))

The r2_score for this dataset with XGboost 0.9989872949201639
The mean of cross val score with r2_score with XGBoost 0.9991207983335213


# Apply GridsearchCv to the XGBoost to search the best results

In [47]:
n_estimators=[200,300,500,800,1000]
learning_rate=[0.01,0.001,0.001,0.05,0.005]
max_depth=[6,8,10,18,20,26,32]
subsample=[0.4,0.6,0.8,1]
colsample_bytree=[0.4,0.6,0.8,1]
tree_method=['hist']
device = ['cpu']

params_grid = { 'n_estimators' : n_estimators, 'learning_rate' : learning_rate, 'max_depth' : max_depth,
    'subsample' : subsample,
    'colsample_bytree' : colsample_bytree ,
    'tree_method' : tree_method,
    'device' : device 
}
print(params_grid)

from sklearn.model_selection import GridSearchCV
xg = XGBRegressor()
search = GridSearchCV(xg,params_grid, scoring = 'r2',cv=10, verbose=3 )
#search.fit(X_train,y_train )

{'n_estimators': [200, 300, 500, 800, 1000], 'learning_rate': [0.01, 0.001, 0.001, 0.05, 0.005], 'max_depth': [6, 8, 10, 18, 20, 26, 32], 'subsample': [0.4, 0.6, 0.8, 1], 'colsample_bytree': [0.4, 0.6, 0.8, 1], 'tree_method': ['hist'], 'device': ['cpu']}


In [48]:
from sklearn.datasets import make_classification

X_c, y_c = make_classification(n_samples=10000, n_features=20, n_classes=3,n_informative=15, random_state=42)
X_c

array([[ 3.02469006e-01,  2.05223469e+00, -2.95351494e+00, ...,
         9.33550242e-02, -4.09893358e+00,  4.84405828e-01],
       [ 6.38026542e-02,  2.46296860e-03,  1.94618613e+00, ...,
         1.82855230e+00,  1.42848039e+00, -3.88251584e-01],
       [-1.83931155e+00,  3.20394113e+00, -8.53649929e-01, ...,
         2.10548495e-01,  1.07865071e+00,  1.63062297e+00],
       ...,
       [-5.28051046e-01,  1.26760120e+00,  9.54695388e-01, ...,
        -5.43696379e+00, -1.61465700e+00, -4.72332336e+00],
       [-2.47661869e+00,  1.51908604e+00, -8.03683361e-02, ...,
        -1.76479339e+00, -2.62585618e-01,  6.01789323e-02],
       [-4.63758729e+00,  1.58634223e+00, -4.29235208e-02, ...,
        -1.24750600e+00, -3.83709058e+00,  1.19848844e+00]])

In [49]:
y_c

array([0, 1, 2, ..., 1, 0, 2])

In [52]:
from sklearn.model_selection import train_test_split

# X = features, y = target
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_c, y_c, test_size=0.2, random_state=42)

# Apply Logistic Regression with this dataset 

In [59]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 
from sklearn.model_selection import cross_val_score 
reg = LogisticRegression()
reg.fit(X_train_c,y_train_c)
y_reg_predict = reg.predict(X_test_c)
score = accuracy_score(y_test_c,y_reg_predict)
print('The accuracy_score for this dataset with Logistic Regresscion',score)
cv_result = cross_val_score(reg,X_c,y_c,scoring='accuracy',cv=10,n_jobs=-1 )
print('The mean of cross val score with accuracy with Logistic Regresscion',np.mean(cv_result))


The accuracy_score for this dataset with Logistic Regresscion 0.665
The mean of cross val score with accuracy with Logistic Regresscion 0.6703


# Apply XGBoost Classification on this dataset

In [68]:
from xgboost import XGBClassifier 
model = XGBClassifier( n_estimators=300,learning_rate=0.05,max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    device='cpu',
    objective='multi:softprob',
    random_state=42)
model.fit(X_train_c, y_train_c)
# 4. Make predictions
predictions = model.predict(X_test_c)
score = accuracy_score(y_test_c,predictions)
print('The accracy_score for this dataset with XGboost',score)
cv_result_c = cross_val_score(model,X_c,y_c,scoring='accuracy',cv=10,n_jobs=-1 )
accu = (cv_result_c.mean())
print('The mean of cross val score with accracy_score with XGBoost',(accu))

The accracy_score for this dataset with XGboost 0.9165
The mean of cross val score with accracy_score with XGBoost 0.9113999999999999
